### ISSUE TITLE
Packages hidden from indexer

### ISSUE THREAD

**Issue by tobyink** [bluefeet/MooseX-SingleArg#5]
Hiding packages like `MooseX::SingleArg::Meta::Object` from the CPAN indexer means that you don't get first-come permission on them and somebody else could release a distribution containing a package of that name. Also means that the code is harder to find for anybody looking for it. (The files don't show up on metacpan's interface unless you choose to browse through the distribution's contents.) And means that someone running:

    $ cpanm MooseX::SingleArg::Meta::Object

because they got an error about a missing package, won't have any luck.

I know this is a minor nitpick, but I can't really see of any advantages of them being non-indexed.

**Comment by bluefeet** [comment]
How dare you try to make things better.
